Repository CLIMADA-project/climada_python, pull requests merged in 2021-04, with the labels that each got.

#180 New module SupplyChain
  climada.conf
  climada/conf/climada.conf
  climada/engine/__init__.py
  climada/engine/supplychain.py
  climada/engine/test/data/WIOTtest_Nov16_ROW.xlsb
  climada/engine/test/test_supplychain.py
  doc/tutorial/climada_engine_SupplyChain.ipynb
  requirements/env_climada.yml
Labels: new module

#166 Fix to TCtracks.to_geodataframe
  climada/hazard/tc_tracks.py
  climada/hazard/test/data/tracks-antimeridian/1980052S16155.nc
  climada/hazard/test/data/tracks-antimeridian/2018079S09162.nc
  climada/hazard/test/test_tc_tracks.py
Labels: enhancement

#162 Feature/forecast
  climada/conf/climada.conf
  climada/engine/forecast.py
  climada/engine/test/test_forecast.py
  climada/hazard/storm_europe.py
  climada/hazard/test/test_storm_europe.py
  doc/tutorial/climada_engine_Forecast.ipynb
  doc/tutorial/climada_hazard_StormEurope.ipynb
Labels: new module

#131 Feature/uncertainty
  climada/conf/climada.conf
  climada/engine/uncertainty/__init__.py
  climada/engine/uncertainty/base.py
  climada/engine/uncertainty/test/test_uncertainty.py
  climada/engine/uncertainty/unc_cost_benefit.py
  climada/engine/uncertainty/unc_impact.py
  climada/engine/uncertainty/unc_robustness.py
  climada/util/test/test_select.py
  climada/util/test/test_value_representation.py
  climada/util/value_representation.py
  doc/tutorial/climada_engine_uncertainty.ipynb
  doc/tutorial/img/UncertaintySensitivity.jpg
  requirements/env_climada.yml
Labels: new module

#181 Guides update
  doc/guide/Guide_CLIMADA_Tutorial.ipynb
  doc/guide/Guide_Configuration.ipynb
  doc/guide/Guide_Euler.ipynb
  doc/guide/Guide_Git_Development.ipynb
  doc/guide/Guide_Installation.ipynb
  doc/guide/Guide_Introduction.ipynb
  doc/guide/Guide_Miscellaneous.ipynb
  doc/guide/Guide_Py_Performance.ipynb
  doc/guide/Guide_PythonDos-n-Donts.ipynb
  doc/guide/Guide_Reviewer_Checklist.ipynb
  doc/guide/Guide_Sidenote_Parameters.ipynb
  doc/guide/Guide_get_started.ipynb
  doc/guide/coding_conventions.rst
  doc/guide/configuration.rst
  doc/guide/data_dependencies.rst
  doc/guide/developer.rst
  doc/guide/git_flow.rst
  doc/guide/install.rst
  doc/guide/install_cluster.rst
  doc/guide/introduction.rst
  doc/guide/reviewer_checklist.rst
  doc/guide/tutorial.rst
  doc/index.rst
Labels: enhancement

#173 Feature/event impact2annual impact
  climada/util/test/test_yearsets.py
  climada/util/yearsets.py
  doc/tutorial/climada_util_yearsets.ipynb
Labels: new module

#206 Improve speed of subsetting an Impact by centroids
  climada/engine/impact.py
  climada/entity/exposures/base.py
  climada/util/coordinates.py
  climada/util/test/test_coordinates.py
Labels: enhancement

#201 Feature/country numeric2iso
  climada/util/coordinates.py
  climada/util/test/test_coordinates.py
Labels: enhancement

#208 Avoid some errors by coercing some Impact.select() input vars
  climada/engine/impact.py
  climada/engine/test/test_impact.py
Labels: enhancement

#204 Update antimeridian handling util.plot.geo_scatter_from_array
  climada/util/plot.py
Labels: enhancement

#205 Use pycountry instead of iso3166 for country code lookup
  climada/engine/forecast.py
  climada/engine/impact_data.py
  climada/engine/supplychain.py
  climada/entity/exposures/black_marble.py
  climada/entity/exposures/crop_production.py
  climada/entity/exposures/gdp_asset.py
  climada/entity/exposures/litpop.py
  climada/entity/exposures/spam_agrar.py
  climada/entity/exposures/test/test_base.py
  climada/entity/exposures/test/test_gdp_asset.py
  climada/hazard/base.py
  climada/hazard/centroids/test/test_vec_ras.py
  climada/hazard/emulator/geo.py
  climada/hazard/low_flow.py
  climada/hazard/river_flood.py
  climada/hazard/test/test_base.py
  climada/hazard/test/test_flood.py
  climada/hazard/test/test_landslide.py
  climada/hazard/test/test_tc_tracks.py
  climada/hazard/trop_cyclone.py
  climada/test/test_LitPop.py
  climada/test/test_blackmarble.py
  climada/util/constants.py
  climada/util/coordinates.py
  climada/util/test/test_coordinates.py
  requirements/env_climada.yml
  setup.py
Labels: dependencies, enhancement

#207 Plots improvements
  climada/hazard/base.py
  climada/util/plot.py
Labels: enhancement
