Repository CLIMADA-project/climada_python, pull requests merged in 2021-03, with the labels that each got.

#170 read_ibtracs_netcdf: fix ROCI estimate
  climada/hazard/tc_tracks.py
  climada/hazard/test/test_tc_tracks.py
Labels: bug

#168 read_ibtracs_netcdf: fix for tracks crossing antimeridian
  climada/hazard/tc_tracks.py
  climada/hazard/test/test_tc_tracks.py
Labels: bug

#174 Feature/scipy_16_update
  climada/entity/exposures/test/test_black_marble.py
Labels: bug

#138 Restructure xarray dataset in TCForecast tracks
  climada/hazard/tc_tracks_forecast.py
  climada/hazard/test/test_tc_tracks_forecast.py
Labels: bug

#171 Feature/categorical plot
  climada/util/plot.py
  climada/util/test/test_plot.py
  climada/util/test/test_value_representation.py
Labels: enhancement

#184 Exposures: error message on item access
  climada/entity/exposures/base.py
  climada/entity/exposures/test/test_base.py
Labels: user-friendliness

#120 Fixed bugs and code clean up of isimip crop module
  climada/entity/exposures/crop_production.py
  climada/entity/exposures/test/test_crop_production.py
  climada/hazard/relative_cropyield.py
  climada/hazard/test/test_relative_cropyield.py
  climada/test/test_cropyield_integr.py
  climada/util/coordinates.py
  climada/util/test/test_coordinates.py
Labels: bug, fixed
